[package]
name = "head-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.82"
assert_cmd = "2.0.14"
clap = { version = "4.5.4", features = ["derive"] }
predicates = "3.1.0"
pretty_assertions = "1.4.0"
rand = "0.8.5"
